image: node:15.0.1-alpine

stages:
  - pre-test
  - test
  - build
  - e2e-test
  - publish

variables:
  DOCKER_REPOSITORY: mendersoftware/gui
  DOCS_VERSION: development

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-docker-build.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'

test:lint:
  stage: test
  except:
    - master
    - /^saas-[a-zA-Z0-9.]+$/
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run lint

test:acceptance:
  stage: e2e-test
  except:
    - /^saas-[a-zA-Z0-9.]+$/
  image: tiangolo/docker-with-compose
  dependencies:
    - build:docker
  services:
    - docker:19.03.5-dind
  before_script:
    - export DOCKER_TAG=${CI_COMMIT_REF_SLUG:-master}
    - export SERVICE_IMAGE=${DOCKER_REPOSITORY}:${DOCKER_TAG}
    - apk add --no-cache bash git wget
    - wget -qP tests/e2e_tests/cypress/fixtures "https://dgsbl4vditpls.cloudfront.net/mender-demo-artifact.mender"
  script:
    - docker load -i image.tar
    - docker tag $SERVICE_IMAGE $DOCKER_REPOSITORY:pr
    - git clone --single-branch https://github.com/mendersoftware/integration.git
    - GUI_REPOSITORY=$(pwd) INTEGRATION_PATH=$(pwd)/integration ./tests/e2e_tests/run
    - docker rmi $DOCKER_REPOSITORY:pr
  artifacts:
    expire_in: 2w
    paths:
      - screenshots
      - logs
    when: on_failure

test:unit:
  stage: test
  except:
    - /^saas-[a-zA-Z0-9.]+$/
  image: node:14-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run test
  artifacts:
    expire_in: 2w
    paths:
      - coverage

test:docs-links:
  stage: test
  except:
    - /^(staging|saas-[a-zA-Z0-9.]+)$/
  before_script:
    - apk add --no-cache curl
  script:
    - links=$(grep -r docs.mender.io src/ | grep -v snapshots | sed -e 's,\${docsVersion},'${DOCS_VERSION}'/,g' | egrep -o 'https?://[^ `]+' | sort | uniq)
    - error=0
    - for url in $links; do
    -   if ! curl --output /dev/null --silent --head --fail $url; then
    -     error=1
    -     echo "[ko] $url"
    -   else
    -     echo "[ok] $url"
    -   fi
    - done
    - if [ $error -gt 0 ]; then
    -   exit 1
    - fi

test:docs-links:hosted:
  extends: test:docs-links
  only:
    - /^(staging|saas-[a-zA-Z0-9.]+)$/
  except: []
  variables:
    DOCS_VERSION: hosted

test-prep:
  stage: pre-test
  image: docker
  services:
    - docker:19.03.5-dind
  script:
    - docker run --rm --entrypoint "/bin/sh" -v $(pwd):/extract mendersoftware/mender-stress-test-client -c "cp mender-stress-test-client /extract/"
  only:
    - staging
  artifacts:
    paths:
      - mender-stress-test-client
    expire_in: 30 days

test:staging-deployment:
  # Allow failure until timing issues are resolved
  allow_failure: true
  image:
    name: cypress/included:5.4.0
    # cypress/included images have entrypoint set to "cypress"
    # which conflicts with GitLab CI wrapper shell script
    entrypoint: ['']
  stage: .post
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
  dependencies:
    - test-prep
  variables:
    CI: 1
    CYPRESS_BASE_URL: https://staging.hosted.mender.io/
    SERVER_URL: https://staging.hosted.mender.io
    DEVICE_TYPE: qemux86-64
  before_script:
    - mv mender-stress-test-client tests/e2e_tests/ && cd tests/e2e_tests
    - wget -qP cypress/fixtures "https://dgsbl4vditpls.cloudfront.net/mender-demo-artifact.mender"
    - apt-get install -qy musl-dev
  script:
    - npm ci --cache .npm --prefer-offline
    - npx cypress verify
    - npm run ciTest
  only:
    - staging
  when: delayed
  start_in: 30 minutes
  artifacts:
    expire_in: 2w
    paths:
      - tests/e2e_tests/cypress/screenshots
      - logs
    when: on_failure

publish:tests:
  stage: publish
  except:
    - /^saas-[a-zA-Z0-9.]+$/
  dependencies:
    - test:unit
  script:
    - export CI_BUILD_REF=${CI_COMMIT_SHA}
    - export CI_BUILD_REF_NAME=${CI_COMMIT_REF_NAME}
    - export CI_BUILD_NAME=${CI_JOB_NAME}
    - export CI_BUILD_ID=${CI_JOB_ID}
    - export CI_MERGE_REQUEST_IID=${CI_COMMIT_BRANCH#pr_}
    - export COVERALLS_FLAG_NAME=unittests
    - npm i -g coveralls
    - coveralls < coverage/lcov.info

publish:disclaimer:
  stage: publish
  image: docker:git
  services:
    - docker:19.03.5-dind
  script:
    - docker build -f Dockerfile.disclaimer -t disclaimer .
    - docker run --rm --entrypoint "/bin/sh" -v $(pwd):/extract disclaimer -c "cp disclaimer.txt /extract/"
    - docker image rm disclaimer
  artifacts:
    expire_in: 2w
    paths:
      - disclaimer.txt
  only:
    - /^(master|staging|[0-9]+\.[0-9]+\.x)$/
